services:
  backend:
    build:
      context: ./backend
    container_name: app-backend
    env_file:
      - ./backend/.env
    environment:
      - APP_ENV=production
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: app-frontend
    ports:
      - "127.0.0.1:8080:8080"
      - "0.0.0.0:80:8080"
    restart: always
    depends_on:
      - backend
